apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nido
resources:
  - namespace.yaml
  - pvc.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
# Uncomment to enable the Ingress:
#   - ingress.yaml